### ISSUE TITLE
请将common_utils与flustars 相关工具类移除，谢谢！

### ISSUE THREAD

**Issue by Sky24n** [MeandNi/Flutter_CommonApp#2]
common_utils与flustars这个两个工具类库是作者花了很多时间和心思开发的开源库，请勿copy源码，敬请谅解！如果大家都像你这样copy，那么我的库谁来用？！
使用方式：
```yaml
dependencies:
  common_utils: x.x.x  #latest version
  flustars: x.x.x  #latest version
```
